export interface CinematchFilm {
  id: number;
  title: string;
  year: number;
  director: string;
  tags: string[];
  blurb: string;
  why: { cosy: number; thinky: number; funny: number; tense: number; romantic: number };
  streaming: string;
  runtime: number;
  rating: string;
  colors: [string, string, string];
  stripe: 'horizontal' | 'diagonal' | 'vertical' | 'burst' | 'flame' | 'splash' | 'neon';
  posterUrl: string;
}

export const CINEMATCH_FILMS: CinematchFilm[] = [
  {
    id: 1,
    title: 'The Grand Budapest Hotel',
    year: 2014,
    director: 'Wes Anderson',
    tags: ['whimsical', 'symmetrical', 'witty', 'pastel', 'stylised'],
    blurb: 'A concierge and his lobby boy, a stolen painting, a confection of a film.',
    why: { cosy: 70, thinky: 40, funny: 75, tense: 45, romantic: 35 },
    streaming: 'Disney+',
    runtime: 99,
    rating: 'PG-13',
    colors: ['#E8A4C4', '#F0C8A8', '#C8A0B4'],
    stripe: 'horizontal',
    posterUrl: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
  },
  {
    id: 2,
    title: 'Moonlight',
    year: 2016,
    director: 'Barry Jenkins',
    tags: ['bittersweet', 'intimate', 'poetic', 'melancholic', 'slow'],
    blurb: "A young Black man's life told in three chapters. Luminous and tender.",
    why: { cosy: 15, thinky: 80, funny: 5, tense: 50, romantic: 55 },
    streaming: 'Netflix',
    runtime: 111,
    rating: 'R',
    colors: ['#1A3A5C', '#4A6B8C', '#2C4C6D'],
    stripe: 'diagonal',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg',
  },
  {
    id: 3,
    title: 'Everything Everywhere All at Once',
    year: 2022,
    director: 'Daniels',
    tags: ['chaotic', 'weird', 'emotional', 'wild', 'genre-blending'],
    blurb: 'A laundromat owner saves every possible universe. With hot dog fingers.',
    why: { cosy: 20, thinky: 70, funny: 65, tense: 75, romantic: 30 },
    streaming: 'Amazon Prime',
    runtime: 139,
    rating: 'R',
    colors: ['#FF6B9D', '#FFB84D', '#4DBFB8'],
    stripe: 'burst',
    posterUrl: 'https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg',
  },
  {
    id: 4,
    title: 'Past Lives',
    year: 2023,
    director: 'Celine Song',
    tags: ['bittersweet', 'quiet', 'romantic', 'melancholic', 'slow'],
    blurb: 'Two childhood friends, twenty years, a single question: what if?',
    why: { cosy: 30, thinky: 60, funny: 10, tense: 25, romantic: 90 },
    streaming: 'Mubi',
    runtime: 106,
    rating: 'PG-13',
    colors: ['#2E3B4E', '#7B8FA6', '#C9B8A8'],
    stripe: 'vertical',
    posterUrl: 'https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',
  },
  {
    id: 5,
    title: 'Parasite',
    year: 2019,
    director: 'Bong Joon-ho',
    tags: ['tense', 'sharp', 'dark', 'clever', 'genre-blending'],
    blurb: 'A poor family infiltrates a rich one. Then things get complicated.',
    why: { cosy: 5, thinky: 85, funny: 30, tense: 95, romantic: 10 },
    streaming: 'Mubi',
    runtime: 132,
    rating: 'R',
    colors: ['#3A3A3A', '#C4A876', '#8B6F47'],
    stripe: 'horizontal',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  },
  {
    id: 6,
    title: 'Portrait of a Lady on Fire',
    year: 2019,
    director: 'Céline Sciamma',
    tags: ['romantic', 'poetic', 'slow', 'intimate', 'stylised'],
    blurb: "An 18th-century painter, her subject, and a brief, incandescent summer.",
    why: { cosy: 25, thinky: 65, funny: 5, tense: 30, romantic: 95 },
    streaming: 'Mubi',
    runtime: 122,
    rating: 'NR',
    colors: ['#6B4226', '#E8C896', '#8B5A3C'],
    stripe: 'flame',
    posterUrl: 'https://image.tmdb.org/t/p/w500/2LquGwEhbg3soxSCs9VNyh5VJd9.jpg',
  },
  {
    id: 7,
    title: 'Hot Fuzz',
    year: 2007,
    director: 'Edgar Wright',
    tags: ['funny', 'fast', 'silly', 'british', 'clever'],
    blurb: 'Supercop gets exiled to a village. The village is not what it seems.',
    why: { cosy: 55, thinky: 40, funny: 90, tense: 60, romantic: 15 },
    streaming: 'Netflix',
    runtime: 121,
    rating: 'R',
    colors: ['#D64545', '#4A6B2F', '#8B9467'],
    stripe: 'splash',
    posterUrl: 'https://image.tmdb.org/t/p/w500/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg',
  },
  {
    id: 8,
    title: 'In the Mood for Love',
    year: 2000,
    director: 'Wong Kar-wai',
    tags: ['romantic', 'melancholic', 'stylised', 'slow', 'intimate'],
    blurb: 'Two neighbours in 1960s Hong Kong. A rehearsal of what could be.',
    why: { cosy: 20, thinky: 60, funny: 5, tense: 35, romantic: 95 },
    streaming: 'Mubi',
    runtime: 98,
    rating: 'PG',
    colors: ['#8B1E3F', '#D4A574', '#3A2416'],
    stripe: 'diagonal',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg',
  },
  {
    id: 9,
    title: 'Columbus',
    year: 2017,
    director: 'Kogonada',
    tags: ['quiet', 'architectural', 'slow', 'intimate', 'melancholic'],
    blurb: 'In a town of modernist buildings, two strangers connect.',
    why: { cosy: 45, thinky: 75, funny: 10, tense: 10, romantic: 40 },
    streaming: 'Mubi',
    runtime: 104,
    rating: 'NR',
    colors: ['#E8E4D8', '#7A8B7F', '#4A5856'],
    stripe: 'vertical',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6tk0xmn9k5HjUeXsnhxIa94sFXP.jpg',
  },
  {
    id: 10,
    title: 'The Worst Person in the World',
    year: 2021,
    director: 'Joachim Trier',
    tags: ['bittersweet', 'funny', 'honest', 'romantic', 'chaotic'],
    blurb: "Julie is nearly thirty, in Oslo, figuring it out (or not).",
    why: { cosy: 35, thinky: 55, funny: 45, tense: 25, romantic: 65 },
    streaming: 'Mubi',
    runtime: 121,
    rating: 'R',
    colors: ['#E85D75', '#F4C2C2', '#A8455C'],
    stripe: 'horizontal',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1NxGNQchGBTHXJ6RShLY1IlZqWn.jpg',
  },
  {
    id: 11,
    title: 'Drive',
    year: 2011,
    director: 'Nicolas Winding Refn',
    tags: ['stylised', 'tense', 'cool', 'moody', 'neon'],
    blurb: "A Hollywood stuntman moonlights as a getaway driver. Then he doesn't.",
    why: { cosy: 10, thinky: 45, funny: 5, tense: 90, romantic: 30 },
    streaming: 'Netflix',
    runtime: 100,
    rating: 'R',
    colors: ['#E91E63', '#1A1A2E', '#16213E'],
    stripe: 'neon',
    posterUrl: 'https://image.tmdb.org/t/p/w500/602vevIURmpDfzbnv5Ubi6wIkQm.jpg',
  },
  {
    id: 12,
    title: 'Paddington 2',
    year: 2017,
    director: 'Paul King',
    tags: ['whimsical', 'warm', 'funny', 'british', 'cosy'],
    blurb: 'A bear, a pop-up book, Hugh Grant giving the performance of a lifetime.',
    why: { cosy: 95, thinky: 20, funny: 85, tense: 20, romantic: 20 },
    streaming: 'Netflix',
    runtime: 103,
    rating: 'PG',
    colors: ['#2A5D8F', '#E8B547', '#7FB3D3'],
    stripe: 'splash',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1OJ9vkD5xPt3skC6KguyXAgagRZ.jpg',
  },
];

export const CINEMATCH_TAG_MAP: Record<string, { cat: 'tone' | 'style' | 'pace' | 'flavour'; label: string }> = {
  whimsical:        { cat: 'tone',    label: 'whimsical' },
  symmetrical:      { cat: 'style',   label: 'symmetrical' },
  witty:            { cat: 'tone',    label: 'witty' },
  pastel:           { cat: 'style',   label: 'soft palette' },
  stylised:         { cat: 'style',   label: 'highly stylised' },
  bittersweet:      { cat: 'tone',    label: 'bittersweet' },
  intimate:         { cat: 'tone',    label: 'intimate' },
  poetic:           { cat: 'style',   label: 'poetic' },
  melancholic:      { cat: 'tone',    label: 'melancholic' },
  slow:             { cat: 'pace',    label: 'slow burn' },
  chaotic:          { cat: 'pace',    label: 'chaotic energy' },
  weird:            { cat: 'tone',    label: 'delightfully weird' },
  emotional:        { cat: 'tone',    label: 'emotionally heavy' },
  wild:             { cat: 'pace',    label: 'wild ride' },
  'genre-blending': { cat: 'style',   label: 'genre-blending' },
  quiet:            { cat: 'pace',    label: 'quiet' },
  romantic:         { cat: 'tone',    label: 'romantic' },
  tense:            { cat: 'tone',    label: 'tense' },
  sharp:            { cat: 'tone',    label: 'sharp' },
  dark:             { cat: 'tone',    label: 'dark' },
  clever:           { cat: 'tone',    label: 'clever' },
  funny:            { cat: 'tone',    label: 'funny' },
  fast:             { cat: 'pace',    label: 'fast-paced' },
  silly:            { cat: 'tone',    label: 'silly' },
  british:          { cat: 'flavour', label: 'very british' },
  honest:           { cat: 'tone',    label: 'painfully honest' },
  architectural:    { cat: 'style',   label: 'architectural eye' },
  cool:             { cat: 'tone',    label: 'cool' },
  moody:            { cat: 'tone',    label: 'moody' },
  neon:             { cat: 'style',   label: 'neon-drenched' },
  warm:             { cat: 'tone',    label: 'warm-hearted' },
  cosy:             { cat: 'tone',    label: 'cosy' },
};

export function getStripeGradient(film: { colors: [string, string, string]; stripe: CinematchFilm['stripe'] }): string {
  const [c1, c2, c3] = film.colors;
  const patterns: Record<string, string> = {
    horizontal: `repeating-linear-gradient(180deg, ${c1} 0px, ${c1} 24px, ${c2} 24px, ${c2} 48px, ${c3} 48px, ${c3} 72px)`,
    diagonal:   `repeating-linear-gradient(135deg, ${c1} 0px, ${c1} 20px, ${c2} 20px, ${c2} 40px, ${c3} 40px, ${c3} 60px)`,
    vertical:   `repeating-linear-gradient(90deg, ${c1} 0px, ${c1} 28px, ${c2} 28px, ${c2} 56px, ${c3} 56px, ${c3} 84px)`,
    burst:      `radial-gradient(circle at 50% 50%, ${c1} 0%, ${c2} 40%, ${c3} 80%)`,
    flame:      `linear-gradient(180deg, ${c1} 0%, ${c1} 40%, ${c2} 55%, ${c3} 100%)`,
    splash:     `radial-gradient(ellipse at 30% 30%, ${c1} 0%, ${c2} 45%, ${c3} 100%)`,
    neon:       `linear-gradient(135deg, ${c2} 0%, ${c2} 50%, ${c3} 50%, ${c3} 100%)`,
  };
  return patterns[film.stripe] || patterns.horizontal;
}
