import { useState } from 'react';
import { collection, doc, setDoc, getDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useAuth } from '@/hooks/use-auth';
import { RecommendationRequest } from '@shared/schema';

export interface ChatSession {
  id: string;
  userId: number;
  messages: Array<{
    id: string;
    sender: 'cineMate' | 'user';
    text: string;
    timestamp: string;
  }>;
  preferences: RecommendationRequest;
  customVibes?: string[]; // Store any custom mood/vibe preferences
  personalizedMoods?: string[]; // Store AI-generated personalized moods
  createdAt: string;
  updatedAt: string;
  completed: boolean;
}

export interface VibePreference {
  text: string;
  frequency: number; // How often this vibe was selected
  lastUsed: string;
  source: 'user_custom' | 'ai_generated' | 'predefined';
}

/**
 * Hook for persisting chat sessions and custom vibe preferences to Firestore
 */
export function useChatPersistence() {
  const { user } = useAuth();
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Save a chat session to Firestore
   */
  const saveChatSession = async (
    sessionData: Omit<ChatSession, 'id' | 'userId' | 'createdAt' | 'updatedAt'>
  ): Promise<boolean> => {
    if (!user) {
      setError('User not authenticated');
      return false;
    }

    setIsSaving(true);
    setError(null);

    try {
      const sessionId = `chat_${Date.now()}`;
      const sessionRef = doc(db, 'users', user.id.toString(), 'chat_sessions', sessionId);
      
      const chatSession: ChatSession = {
        id: sessionId,
        userId: user.id,
        ...sessionData,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      await setDoc(sessionRef, {
        ...chatSession,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      });

      console.log(`💬 Chat session saved to Firestore: ${sessionId}`);
      return true;
    } catch (error) {
      console.error('Error saving chat session to Firestore:', error);
      setError('Failed to save chat session');
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  /**
   * Save or update a custom vibe preference
   */
  const saveVibePreference = async (
    vibeText: string,
    source: VibePreference['source'] = 'user_custom'
  ): Promise<boolean> => {
    if (!user) {
      setError('User not authenticated');
      return false;
    }

    setIsSaving(true);
    setError(null);

    try {
      const vibeId = vibeText.toLowerCase().replace(/[^a-z0-9]/g, '_');
      const vibeRef = doc(db, 'users', user.id.toString(), 'vibe_preferences', vibeId);
      
      // Check if vibe already exists
      const existingVibe = await getDoc(vibeRef);
      
      let vibeData: VibePreference;
      if (existingVibe.exists()) {
        // Update existing vibe
        const existing = existingVibe.data() as VibePreference;
        vibeData = {
          text: vibeText,
          frequency: existing.frequency + 1,
          lastUsed: new Date().toISOString(),
          source: existing.source // Keep original source
        };
      } else {
        // Create new vibe
        vibeData = {
          text: vibeText,
          frequency: 1,
          lastUsed: new Date().toISOString(),
          source
        };
      }

      await setDoc(vibeRef, {
        ...vibeData,
        lastUsed: serverTimestamp()
      });

      console.log(`🎭 Vibe preference saved: "${vibeText}" (frequency: ${vibeData.frequency})`);
      return true;
    } catch (error) {
      console.error('Error saving vibe preference to Firestore:', error);
      setError('Failed to save vibe preference');
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  /**
   * Save multiple personalized moods generated by AI
   */
  const savePersonalizedMoods = async (moods: string[]): Promise<boolean> => {
    if (!user || !moods.length) return false;

    setIsSaving(true);
    setError(null);

    try {
      // Save each mood as a vibe preference
      const savePromises = moods.map(mood => 
        saveVibePreference(mood, 'ai_generated')
      );
      
      await Promise.all(savePromises);
      
      console.log(`🤖 Saved ${moods.length} AI-generated personalized moods`);
      return true;
    } catch (error) {
      console.error('Error saving personalized moods:', error);
      setError('Failed to save personalized moods');
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  /**
   * Get user's most frequently used vibe preferences
   */
  const getTopVibePreferences = async (limit: number = 10): Promise<VibePreference[]> => {
    if (!user) return [];

    try {
      const vibesRef = collection(db, 'users', user.id.toString(), 'vibe_preferences');
      // Note: We would need to implement ordering by frequency in a real query
      // For now, this is a placeholder that would need proper Firestore querying
      console.log(`📊 Would fetch top ${limit} vibe preferences for user ${user.id}`);
      return [];
    } catch (error) {
      console.error('Error fetching vibe preferences:', error);
      return [];
    }
  };

  return {
    saveChatSession,
    saveVibePreference,
    savePersonalizedMoods,
    getTopVibePreferences,
    isSaving,
    error
  };
}